# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eeb7341f32789ff636073b4a4b0fbfe3ee10d75923c1a651198841846f8d47397847f23165254d5e9d1d39a4a458fd5b242a6924aa785fc24b594f437fde5ac8
  mailer_user_name: <%= ENV['MAILER_USER_NAME'] %>
  mailer_pass: <%= ENV['MAILER_PASS'] %>
  devise_secret: <%= ENV.fetch("DEVISE_SECRET", "11f81d8f5370bb8bedb253a270caf7150dcb5d6f9ead532e5adae8b6b1963434554f245a5bb5697f76157d64128c43aa5d8366fd86c889c27e91560bcd58a232") %>
  mailer_mail_address: <%= ENV['MAILER_MAIL_ADDRESS'] %>
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  sidekiq_secret: <%= ENV.fetch("SIDEKIQ_SECRET", "redis://localhost:6379/0") %>

test:
  mailer_user_name: <%= ENV['MAILER_USER_NAME'] %>
  mailer_pass: <%= ENV['MAILER_PASS'] %>
  mailer_mail_address: <%= ENV['MAILER_MAIL_ADDRESS'] %>
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  secret_key_base: 3912a254ae05d8c49eff94892768f794e91de2fa258e96851732f9cf1f4b7f48b74e95b7eb6cd74fc85aafc5f3330301f9cebc9b7d2c0c98fb58962fba640be2
  devise_secret: <%= ENV.fetch("DEVISE_SECRET", "11f81d8f5370bb8bedb253a270caf7150dcb5d6f9ead532e5adae8b6b1963434554f245a5bb5697f76157d64128c43aa5d8366fd86c889c27e91560bcd58a232") %>
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret: <%= ENV["DEVISE_SECRET"] %>
  sidekiq_secret: <%= ENV["SIDEKIQ_SECRET"] %>
